insert into Styles ('name') values ('GPS Topical Anesthetic');
insert into Styles ('name') values ('ATORVASTATIN CALCIUM');
insert into Styles ('name') values ('Isopto Atropine');
insert into Styles ('name') values ('LORAZEPAM');
insert into Styles ('name') values ('Nigrospora sphaerica');
insert into Styles ('name') values ('Allergy Medicine');
insert into Styles ('name') values ('Equate Ibuprofen');
insert into Styles ('name') values ('Tacrolimus');
insert into Styles ('name') values ('Terbinafine Hydrochloride');
insert into Styles ('name') values ('LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25');
insert into Styles ('name') values ('Hydromarine');
insert into Styles ('name') values ('ShopRight Childrens Nighttime Cold and Cough');
insert into Styles ('name') values ('Hydroxychloroquine Sulfate');
insert into Styles ('name') values ('Linzess');
insert into Styles ('name') values ('Treatment Set TS351200');
insert into Styles ('name') values ('BENZTROPINE MESYLATE');
insert into Styles ('name') values ('Valsartan and Hydrochlorothiazide');
insert into Styles ('name') values ('Gentle Laxative');
insert into Styles ('name') values ('Daytime Nighttime Non-Aspirin Cold Formula Multi-Symptom');
insert into Styles ('name') values ('Dog Fennel');
